### ISSUE TITLE
Evaluator problem 

### ISSUE THREAD

**Issue by SeifElabsy** [a-h-i/evaluator#1]
I can not see my team nor their submissions on the evaluator for the game course 
40-6357 
seif elabsy

**Comment by a-h-i** [comment]
Hello @SeifElabsy Yes for this milestone you are not able to view team stats. 
This milestone evaluator is used for saving your submissions only. Only one member of the team needs to submit. During the next milestone you will be able to see the realtime test results and your team's submissions and their results.
